### ISSUE TITLE
delete.tv.unwatched.py: list index out of range

### ISSUE THREAD

**Issue by rollecode** [ASK-ME-ABOUT-LOOM/purgeomatic#17]
I have 38 series in sonarr.

--------------------------------------
2023-11-09T19:18:04.469541

Error message:
list index out of range

**Comment by ASK-ME-ABOUT-LOOM** [comment]
Not much to go on, here. I assume you're using the `delete.tv.unwatched.py` script? Are you getting any other output? 

I've updated the script to add a try/except block in the only spot where I believe it could be failing like that. I'm not sure what's going on there, but I _think_ this will fix it, barring additional messages. Please let me know if this works, because I'll make the same alterations to the `delete.movies.unwatched.py` script.

**Comment by rollecode** [comment]
Yes, running delete.tv.unwatched.py. Movie script works fine.

Right now getting this with the latest changes (full output):

```
DRY_RUN enabled!
--------------------------------------
2023-11-10T08:47:32.221724
ERROR: Unable to get TVDBID for Battlestar Galactica even though it appears to be set in Tautulli. Falling back to title-based matching. Error message:list index out of range
Total space reclaimed: 0.00GB
```

**Comment by ASK-ME-ABOUT-LOOM** [comment]
Try refreshing your metadata in Plex.

In the Plex web UI, click the library, then the three-dot menu &rarr; manage library &rarr; refresh all metadata.

**Comment by ASK-ME-ABOUT-LOOM** [comment]
I believe this issue is closed. Feel free to comment back if it's persisting.

**Comment by rollecode** [comment]
> Try refreshing your metadata in Plex.
> 
> In the Plex web UI, click the library, then the three-dot menu → manage library → refresh all metadata.

This didn't do it. I still have the same problem. Been removing TV series by hand.
